version: '3'

services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - ./${APP_NAME}:/var/www/html
    networks:
      - project-network
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./${APP_NAME}:/var/www/html
    ports:
      - ${NGINX_PORT}:80
     
    depends_on:
      - php
    networks:
      - project-network
  node:
    image: node:latest
    volumes:
      - ./${APP_NAME}/react:/usr/src/app
    command: "npm run watch"
    depends_on:
      - php
      - nginx
    networks:
      - project-network
  db:
    image: mariadb:latest
    ports:
      - ${DB_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - project-network
networks:
  project-network: 
    name: ${APP_NAME}-network