name: Laravel & React Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Build npm package
        run: |
          cd norsk-studying/react/
          npm install
          npm run build
      - name: deploy
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 91.108.101.6
          ssh-port: 65002
      - name: Copy dist files
        run: |
          cd domains/api.tongue-twist-norway.com/norsk-studying/
          cp -r react/dist/* ../../tongue-twist-norway.com/public_html/.
      - name: Laravel migrations
        run: php artisan migrate
